/** A character preview, rendered without the harness.
 *
 *  POST starts one and answers immediately with a job id; GET reports on it. The
 *  render itself is detached, so a reloaded tab can pick the job back up instead
 *  of abandoning two minutes of GPU time.
 *
 *  This is the one render in the app that skips the harness, and the reason is
 *  narrow enough to write down: a preview has nothing to decide. Three fixed
 *  models that have been on the volume since August, a graph this app generates
 *  itself, no adapters, no per-clip stack. Everything the harness contributes to
 *  a clip — provisioning the models a shot happens to need, retrying, keeping us
 *  on the author's rails — has no work to do here, while the machinery still
 *  costs a workspace, an agent, and a second Modal job whose container exits
 *  before the render's container starts.
 *
 *  Measured: 150s through the harness, 112s direct. A quarter, not the two
 *  thirds I guessed — the container cold start is Modal's and does not go away.
 */
import { env } from '$env/dynamic/private';
import { error, json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { renderDirect } from '../../modal.server';
import { checkDescription } from '../../minors.server';
import { failJob, finishJob, getJob, startJob } from '../../anchorjobs.server';

/** The anchor bundle is generated by this same app; asking for it over HTTP
 *  keeps one definition of the graph rather than two. */
const GRAPH_URL = '/studio/api/anchorwf/workflow.json';

/** Node ids in that graph. They are stable because we cut it ourselves and the
 *  route refuses to serve a graph missing any of them. */
const NODE_PROMPT = '10';
const NODE_SAMPLER = '28';
const NODE_SAVE = '75';

/** Same tier the sheets are pinned to. Measured: the card makes no difference to
 *  a render that is almost entirely file reading, so this is the cheap one. */
const GPU = 'l40s' as const;

/** Credentials live in the harness's env file rather than this app's, because
 *  that is where they already were and a second copy of a secret is a second
 *  thing to leak. Read per call so a rotation takes effect without a restart. */
function harnessEnv(): Record<string, string> {
	const out: Record<string, string> = {};
	const p = join(homedir(), 'auteur', '.env');
	if (!existsSync(p)) return out;
	for (const line of readFileSync(p, 'utf8').split('\n')) {
		const m = /^([A-Za-z0-9_]+)=(.*)$/.exec(line.trim());
		if (m) out[m[1]] = m[2];
	}
	return out;
}

export const GET: RequestHandler = async ({ url }) => {
	const id = url.searchParams.get('job') ?? '';
	const job = getJob(id);
	if (!job) return json({ ok: false, error: 'no such preview' });
	return json({
		ok: true,
		phase: job.phase,
		error: job.error,
		elapsedSec: job.elapsedSec,
		description: job.description,
		seed: job.seed,
		...(job.phase === 'done' ? { url: `/studio/api/anchor/img/${job.id}` } : {})
	});
};

export const POST: RequestHandler = async ({ request, fetch }) => {
	let body: { description?: unknown; seed?: unknown };
	try {
		body = await request.json();
	} catch {
		throw error(400, 'Body must be JSON');
	}
	const description = typeof body.description === 'string' ? body.description.trim() : '';
	if (!description) throw error(400, 'Missing description');

	// The same gate every other path runs. A render that skips the harness must
	// not also skip this.
	const gate = checkDescription(description);
	if (gate.refuse) return json({ ok: false, error: gate.refuse });

	const seed = Number.isFinite(Number(body.seed))
		? Math.floor(Number(body.seed))
		: Math.floor(Math.random() * 1_000_000_000);

	const e = harnessEnv();
	const s3 = {
		accessKey: e.AWS_ACCESS_KEY ?? '',
		secretKey: e.AWS_SECRET_KEY ?? '',
		region: e.AWS_REGION ?? '',
		bucket: e.S3_BUCKET ?? ''
	};
	if (!s3.accessKey || !s3.secretKey || !s3.region || !s3.bucket) {
		return json({
			ok: false,
			error: 'S3 is not configured in ~/auteur/.env — a direct render has nowhere to put the picture'
		});
	}
	const workspace = e.MODAL_WORKSPACE || env.MODAL_WORKSPACE || '';
	if (!workspace) {
		return json({ ok: false, error: 'MODAL_WORKSPACE is not set in ~/auteur/.env' });
	}

	let graph: Record<string, { inputs?: Record<string, unknown> }>;
	try {
		const res = await fetch(GRAPH_URL);
		if (!res.ok) return json({ ok: false, error: `the anchor graph answered ${res.status}` });
		graph = (await res.json()) as typeof graph;
	} catch (err) {
		return json({ ok: false, error: `could not read the anchor graph — ${err}` });
	}
	for (const n of [NODE_PROMPT, NODE_SAMPLER, NODE_SAVE]) {
		if (!graph[n]?.inputs) {
			return json({ ok: false, error: `the anchor graph has no node ${n} — it has been recut` });
		}
	}

	// Straight into the graph. No ports, no manifest, no agent deciding what to
	// pass: the two values that vary are written where they land.
	graph[NODE_PROMPT].inputs!.value = description;
	graph[NODE_SAMPLER].inputs!.seed = seed;

	const id = `anchor-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
	startJob(id, description, seed);

	// Detached on purpose: the answer below is the job id, not the picture.
	void renderDirect(
		{
			renderId: id,
			workflow: graph,
			target: { workspace, gpu: GPU, cuda: '13', comfy: '0.32.0' },
			s3,
			outputs: [{ name: 'anchor_image.png', nodeId: NODE_SAVE, key: `studio-direct/${id}.png` }],
			timeoutSec: 900
		},
		fetch
	)
		.then(async (r) => {
			if (!r.ok) {
				failJob(id, r.error);
				return;
			}
			const file = r.files[0];
			if (!file?.url) {
				failJob(id, 'the render finished without producing a picture');
				return;
			}
			try {
				const got = await fetch(file.url);
				if (!got.ok) {
					failJob(id, `the picture could not be fetched back — ${got.status}`);
					return;
				}
				finishJob(id, new Uint8Array(await got.arrayBuffer()), r.elapsedSec);
			} catch (err) {
				failJob(id, `the picture could not be fetched back — ${err}`);
			}
		})
		.catch((err) => failJob(id, String(err)));

	return json({ ok: true, job: id, seed });
};
