/** The reference images for one clip, kept where the bundle generator can reach
 *  them.
 *
 *  Staged references live in one shared area and are cleared the moment they are
 *  imported into a workspace, which is exactly when the bundle for that clip
 *  still needs them: the generator is asked for the graph minutes later, when a
 *  render actually starts. So each launch takes its own copy first.
 *
 *  Named `ref_0`, `ref_1` … deliberately. The harness's asset mechanism matches
 *  a bare filename appearing in the graph against the bundle's `assets` list and
 *  substitutes a URL for it, so the name in the LoadImage node and the name in
 *  the assets list have to be the same short, predictable string — and the
 *  user's own filenames are neither. The extension is kept because it is part of
 *  the basename that has to match, and because a decoder is entitled to it.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { extname, join } from 'node:path';

const DIR = join(homedir(), 'auteur', 'studio-library', 'refs-run');

/** Slugs are generated by the page as `direct-<base36>-<base36>`, but this
 *  builds a filesystem path, so it gets checked rather than trusted. */
const SLUG_OK = /^[a-z0-9-]{4,80}$/;

function runDir(slug: string): string | null {
	if (!SLUG_OK.test(slug)) return null;
	return join(DIR, slug);
}

/** Keep a copy of this launch's references and return the basenames the graph
 *  should use. Empty for a launch with none, which is the common case and must
 *  stay free. */
export function stashRefs(slug: string, files: { bytes: Buffer; name: string }[]): string[] {
	const dir = runDir(slug);
	if (!dir || !files.length) return [];
	try {
		mkdirSync(dir, { recursive: true });
		const names: string[] = [];
		files.forEach((f, i) => {
			const ext = (extname(f.name) || '.png').toLowerCase().slice(0, 5);
			const base = `ref_${i}${ext}`;
			writeFileSync(join(dir, base), f.bytes);
			names.push(base);
		});
		writeFileSync(join(dir, 'index.json'), JSON.stringify(names), 'utf8');
		return names;
	} catch {
		// A launch must not fail because the copy did. It renders without
		// references, which is visibly wrong rather than silently wrong.
		return [];
	}
}

/** The brief a run was launched with, kept beside the references it was given.
 *
 *  Internal renders are deliberately absent from the render log — nobody rates a
 *  turnaround and the browser never watches one, so the row could only ever be
 *  half-written. But removing them took the prompt with it, and the prompt is
 *  the evidence: when a sheet comes back looking like someone else, the first
 *  question is always what words actually reached the GPU. Kept here rather than
 *  put back in the log, so it sits with the pictures it was rendered against and
 *  is pruned on the same schedule.
 */
export function stashBrief(slug: string, prompt: string): void {
	if (!SLUG_OK.test(slug)) return;
	try {
		const dir = join(DIR, slug);
		if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
		writeFileSync(join(dir, 'prompt.txt'), prompt, 'utf8');
	} catch {
		// Evidence is worth having and never worth failing a render for.
	}
}

export function stashedNames(slug: string): string[] {
	const dir = runDir(slug);
	if (!dir || !existsSync(dir)) return [];
	try {
		const idx = join(dir, 'index.json');
		if (existsSync(idx)) {
			const parsed: unknown = JSON.parse(readFileSync(idx, 'utf8'));
			if (Array.isArray(parsed)) return parsed.filter((n): n is string => typeof n === 'string');
		}
		return readdirSync(dir)
			.filter((n) => n.startsWith('ref_'))
			.sort();
	} catch {
		return [];
	}
}

export function readStashed(slug: string, base: string): Buffer | null {
	const dir = runDir(slug);
	// The basename is ours, not the user's, so it can be required to look like
	// ours — which is also what keeps this from serving anything else on disk.
	if (!dir || !/^ref_\d+\.[a-z0-9]{2,4}$/.test(base)) return null;
	const p = join(dir, base);
	try {
		return existsSync(p) ? readFileSync(p) : null;
	} catch {
		return null;
	}
}

/** Older runs' copies, dropped once there are more than a handful. The clips
 *  are the product and are cached elsewhere; these are working files. */
export function pruneStashes(keep = 20): void {
	try {
		if (!existsSync(DIR)) return;
		const dirs = readdirSync(DIR, { withFileTypes: true })
			.filter((d) => d.isDirectory())
			.map((d) => d.name)
			.sort();
		for (const name of dirs.slice(0, Math.max(0, dirs.length - keep))) {
			rmSync(join(DIR, name), { recursive: true, force: true });
		}
	} catch {
		// Housekeeping is not worth failing a launch over.
	}
}

export function contentTypeFor(base: string): string {
	const e = extname(base).toLowerCase();
	if (e === '.jpg' || e === '.jpeg') return 'image/jpeg';
	if (e === '.webp') return 'image/webp';
	if (e === '.gif') return 'image/gif';
	return 'image/png';
}
