/**
 * WorkflowAgent E2E — minimaxh3_t2v_i2v_ref2v_advanced_film_making_foxydit
 *
 * Auto-generated by wf-convert; revised for correct GPU config (h100).
 *
 * T2V mode — no image/video fixture inputs, only a structured text prompt param.
 *
 * Run inside the harness container (standard fat-image deployment):
 *   docker exec -it harness golem repl \
 *     --script-file /work/workflows/minimaxh3_t2v_i2v_ref2v_advanced_film_making_foxydit/e2e-test.ts --yes
 *
 * Dev-tree fallback (local golem server, not via fat image):
 *   WORK_DIR=/path/to/repo-root \
 *   source video-harness/.env && cd video-harness && \
 *   golem repl --script-file ../workflows/minimaxh3_t2v_i2v_ref2v_advanced_film_making_foxydit/e2e-test.ts --yes
 */

// ── CONFIG ───────────────────────────────────────────────────────────────────
const WF_NAME = "minimaxh3_t2v_i2v_ref2v_advanced_film_making_foxydit";
const GPU_TYPE = "h100"; // per workflow.yaml gpu_types: [a100, h100, blackwell]
const TIMEOUT_SEC = 5400; // 90 min per attempt
const PROVISION_TIMEOUT_MS = 60 * 60 * 1000; // 60 min (includes model download ~37 GB)
const RENDER_TIMEOUT_MS = 90 * 60 * 1000; // 90 min for render
const RENDER_POLL_MS = 30_000;

const COMPUTE_BACKEND = process.env.COMPUTE_BACKEND ?? "modal";
const S3_BUCKET = process.env.S3_BUCKET ?? "";
const AWS_REGION = process.env.AWS_REGION ?? "us-east-1";
const AWS_ACCESS_KEY = process.env.AWS_ACCESS_KEY ?? "";
const AWS_SECRET_KEY = process.env.AWS_SECRET_KEY ?? "";
const HF_TOKEN = process.env.HF_TOKEN ?? "";

const missing = [
  ["S3_BUCKET", S3_BUCKET],
  ["AWS_ACCESS_KEY", AWS_ACCESS_KEY],
  ["AWS_SECRET_KEY", AWS_SECRET_KEY],
]
  .filter(([, v]) => !v)
  .map(([k]) => k);
if (missing.length)
  throw new Error(`Missing required env vars: ${missing.join(", ")}`);

// ── golem-ts-bridge //v1 double-slash workaround ──────────────────────────────
// The golem CLI's `-E release` (custom server) config normalizes the server URL
// with a trailing slash (e.g. "http://localhost:9881/"); golem-ts-bridge's
// createAgent()/invokeAgent() concatenate `${baseUrl}/v1/...` verbatim, producing
// "http://localhost:9881//v1/agents/create-agent". The fat-image container has no
// nginx in front of golem to normalize this (unlike the docker-compose dev stack),
// so every agent RPC 404s with "Not Found, not found". Patch it at the fetch layer.
const _origFetch = globalThis.fetch;
(globalThis as any).fetch = (input: any, init?: any) => {
  if (typeof input === "string") input = input.replace(/([^:])\/\/v1\//, "$1/v1/");
  return _origFetch(input, init);
};

// ── FIXTURE FILES ─────────────────────────────────────────────────────────────
const _path = require("node:path") as typeof import("node:path");
const WORK_DIR = process.env.WORK_DIR ?? "/work";
const FIXTURE_DIR = _path.join(WORK_DIR, "workflows", WF_NAME);

// Models are sourced from workflow.yaml via agent.loadFromContent() — no hardcoded WF_MODELS needed.

// ── Render profile ────────────────────────────────────────────────────────────
const RENDER_PROFILE = {
  tier: "standard",
  profile: {
    compute: {
      backend: COMPUTE_BACKEND,
      gpuType: GPU_TYPE,
      timeoutSec: TIMEOUT_SEC,
      maxAttempts: 2,
    },
  },
};

// ── Helpers ───────────────────────────────────────────────────────────────────
const _nodeFs = require("node:fs") as typeof import("node:fs");
const failures: string[] = [];

function check(name: string, cond: boolean, detail: string): void {
  console.log(`  ${cond ? "✓" : "✗"} ${name} — ${detail}`);
  if (!cond) failures.push(`${name}: ${detail}`);
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

async function pollUntilDone(agent: any, renderId: string): Promise<any> {
  const deadline = Date.now() + RENDER_TIMEOUT_MS;
  let lastPhase = "";
  while (Date.now() < deadline) {
    const json = await agent.runStatus(renderId);
    const result = JSON.parse(json ?? "null");
    if (!result)
      throw new Error(`runStatus returned null for renderId "${renderId}"`);
    if (result.phase !== lastPhase) {
      console.log(
        `    phase=${result.phase}  attempts=${result.attempts ?? 0}`,
      );
      lastPhase = result.phase;
    }
    if (result.phase === "succeeded") return result;
    if (result.phase === "failed") {
      const f = result.failure ?? {};
      throw new Error(
        `render failed: kind=${f.kind ?? "?"} — ${f.message ?? "(no message)"}`,
      );
    }
    await sleep(RENDER_POLL_MS);
  }
  throw new Error(`render timed out after ${RENDER_TIMEOUT_MS / 1000}s`);
}

// ── Agent ─────────────────────────────────────────────────────────────────────
const agent = await (globalThis as any).WorkflowAgent.get(
  WF_NAME,
  `e2e-${WF_NAME}-${Date.now()}`,
);

async function teardownAll(): Promise<void> {
  console.log(
    "\n── Teardown ─────────────────────────────────────────────────────",
  );
  try {
    await agent.teardown();
    console.log("  ✓ teardown() completed");
    const st = JSON.parse(await agent.backendStatus());
    check(
      "status after teardown is not provisioned",
      st.status !== "provisioned",
      st.status,
    );
  } catch (err) {
    console.log(`  ✗ teardown() threw: ${err}`);
    failures.push(`teardown: ${err}`);
  }
}

// ── Test execution ────────────────────────────────────────────────────────────
try {
  console.log(`=== WorkflowAgent E2E — ${WF_NAME} ===\n`);

  // 1. Load workflow from local bundle ─────────────────────────────────────────
  // workflow.json and workflow.yaml are read directly from the bind-mounted fixture
  // directory — WorkflowAgent.load() uses workflowJson inline and never fetches sourceUrl.
  console.log(
    "── 1. Load workflow from bundle ─────────────────────────────────",
  );
  const _fs: {
    readFileSync: (p: string, enc: string) => string;
  } = require("node:fs");
  const workflowJson = _fs.readFileSync(
    _path.join(FIXTURE_DIR, "workflow.json"),
    "utf8",
  );
  const workflowYaml = _fs.readFileSync(
    _path.join(FIXTURE_DIR, "workflow.yaml"),
    "utf8",
  );
  console.log(
    `  workflow.json: ${workflowJson.length} bytes   workflow.yaml: ${workflowYaml.length} bytes`,
  );
  check(
    "workflow.json loaded",
    workflowJson.length > 0,
    `${workflowJson.length} bytes`,
  );
  check(
    "workflow.yaml loaded",
    workflowYaml.length > 0,
    `${workflowYaml.length} bytes`,
  );

  // Routes through WorkflowDownloader.buildEntryFromContent() — same path as production workspace.
  const slimManifestJson = await agent.loadFromContent(
    WF_NAME,
    workflowJson,
    workflowYaml,
  );
  const manifest = JSON.parse(slimManifestJson);
  if (manifest.error)
    throw new Error(`loadFromContent failed: ${manifest.error}`);
  console.log(
    `  Loaded: inputs=${manifest.inputs?.length ?? 0} outputs=${manifest.outputs?.length ?? 0}`,
  );
  check(
    "manifest id matches",
    manifest.id === WF_NAME,
    manifest.id ?? "(null)",
  );
  check(
    "no image/video inputs (pure T2V)",
    (manifest.inputs?.length ?? 0) === 0,
    JSON.stringify(manifest.inputs?.map((i: any) => i.name)),
  );
  check(
    "has primary output",
    manifest.outputs?.some((o: any) => o.role === "primary"),
    JSON.stringify(manifest.outputs),
  );

  // 1b. Pre-flight: verify model URLs from YAML ─────────────────────────────────
  console.log(
    "\n── 1b. Pre-flight: verify model URLs ────────────────────────────",
  );
  const _yaml: { parse: (input: string) => any } = require("yaml");
  const parsedYaml = _yaml.parse(workflowYaml);
  for (const model of parsedYaml.models ?? []) {
    for (const f of model.files ?? []) {
      const url = f.url as string;
      if (!url) {
        console.log(`  [skip] ${model.name} — no public URL`);
        continue;
      }
      const headers: Record<string, string> = {};
      if (url.includes("huggingface.co") && HF_TOKEN) {
        headers["Authorization"] = `Bearer ${HF_TOKEN}`;
      }
      const resp = await fetch(url, {
        method: "HEAD",
        redirect: "follow",
        headers,
      });
      check(
        `${model.name} URL resolves`,
        resp.ok,
        `HTTP ${resp.status} — ${url.slice(0, 80)}`,
      );
    }
  }
  if (failures.length > 0)
    throw new Error(`Model URL pre-flight failed:\n${failures.join("\n")}`);

  // 2. Provision ───────────────────────────────────────────────────────────────
  console.log(
    "\n── 2. Provision " + GPU_TYPE + " endpoint ─────────────────────",
  );
  await agent.provision();
  const provDeadline = Date.now() + PROVISION_TIMEOUT_MS;
  let provSummary: any = null;
  while (Date.now() < provDeadline) {
    const st = JSON.parse(await agent.backendStatus());
    if (st.status === "provisioned") {
      provSummary = st;
      break;
    }
    if (st.status === "failed")
      throw new Error(`Provisioning failed: ${st.error}`);
    console.log(`  [${st.status}] dc=${st.dcIndex ?? 0}/${st.dcTotal ?? "?"}`);
    await sleep(25_000);
  }
  if (!provSummary)
    throw new Error(
      `Provision timed out after ${PROVISION_TIMEOUT_MS / 60_000} min`,
    );
  check(
    "provisioned",
    provSummary.status === "provisioned",
    provSummary.status,
  );

  // 3. Read prompt fixture ─────────────────────────────────────────────────────
  // T2V mode: no image/video anchors — only the structured REF2V-format text prompt.
  console.log(
    "\n── 3. Read prompt fixture ───────────────────────────────────────",
  );
  const promptText = _nodeFs
    .readFileSync(_path.join(FIXTURE_DIR, "prompt_positive.txt"), "utf-8")
    .toString()
    .trim();
  check("prompt_positive.txt loaded", promptText.length > 0, `${promptText.length} chars`);

  // 4. Submit render ─────────────────────────────────────────────────────────
  console.log(
    "\n── 4. Submit render ─────────────────────────────────────────────",
  );
  const renderId = await agent.run(
    JSON.stringify(RENDER_PROFILE),
    JSON.stringify({}),
    JSON.stringify({
      prompt_positive: promptText,
      steps: 4,
      video_length: 5.0,
      width: 480,
      height: 864,
      fps: 48,
    }),
    undefined,
  );
  console.log(`  renderId=${renderId}`);
  check("renderId non-empty", renderId.length > 0, renderId);

  // 5. Poll to completion ────────────────────────────────────────────────────
  console.log(
    "\n── 5. Poll to completion ────────────────────────────────────────",
  );
  const result = await pollUntilDone(agent, renderId);
  check(
    "render succeeded",
    result.phase === "succeeded",
    `phase=${result.phase}`,
  );

  // 6. Verify output ─────────────────────────────────────────────────────────
  function _isMp4(b: Uint8Array): boolean {
    // ISO BMFF 'ftyp' box at offset 4
    return b.length >= 8 && b[4] === 0x66 && b[5] === 0x74 && b[6] === 0x79 && b[7] === 0x70;
  }
  function _hexHead(b: Uint8Array, n = 8): string {
    return Array.from(b.slice(0, n)).map((x) => x.toString(16).padStart(2, "0")).join(" ");
  }

  if (result.phase === "succeeded" && result.outputs?.length > 0) {
    console.log(
      "\n── 6. Verify output ─────────────────────────────────────────────",
    );
    for (const out of result.outputs) {
      console.log(`  ${out.filename ?? out.name ?? "output"}: ${out.url}`);
      const r = await fetch(out.url);
      check(`${out.name ?? out.filename} accessible`, r.ok, `HTTP ${r.status}`);
      const raw = new Uint8Array(await r.arrayBuffer());
      check(`${out.name ?? out.filename} is MP4`, _isMp4(raw), `magic=${_hexHead(raw)}`);
    }
  } else {
    check(
      "outputs present",
      (result.outputs?.length ?? 0) > 0,
      JSON.stringify(result.outputs),
    );
  }

  console.log(
    `\n=== ${failures.length === 0 ? "ALL CHECKS PASSED ✓" : failures.length + " CHECK(S) FAILED ✗"} ===`,
  );
  if (failures.length > 0) for (const f of failures) console.log(`  ✗ ${f}`);
} finally {
  await teardownAll();
  if (failures.length > 0)
    throw new Error(
      `${failures.length} e2e check(s) failed:\n${failures.join("\n")}`,
    );
}
